Update block-non-master-branches.yml

diff --git a/.github/workflows/block-non-master-branches.yml b/.github/workflows/block-non-master-branches.yml
--- a/.github/workflows/block-non-master-branches.yml
+++ b/.github/workflows/block-non-master-branches.yml
@@ -1,18 +1,18 @@
-name: Block non-master branches from merging to PROD
+name: Prevent Non-Master Merge into PROD
 
 on:
   pull_request:
     branches:
-      - 'PROD'
+      - PROD
 
 jobs:
-  check-merge:
+  check:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Check if PR is coming from master branch
-        run: |
-          if [ "${{ github.event.pull_request.head.ref }}" != "master" ]; then
-            echo "Error: Pull request must come from the 'master' branch to merge into 'PROD'.";
-            exit 1;
-          fi
+    - name: Check if PR is from master branch
+      run: |
+        if [[ $GITHUB_HEAD_REF != "master" ]]; then
+          echo "Error: You can only merge from the master branch into PROD!";
+          exit 1;
+        fi
